/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.konser_oop2.pembeli;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Gita Aulia Hafid
 */
public class cardRiwayatPanel extends javax.swing.JPanel {

   private String id_det_riwayat;
   
    public cardRiwayatPanel(String id_det_riwayat, String namaKonser, String namaBand, String tanggal, String jam, String lokasi, String kursi, String kategori) {
        this.id_det_riwayat = id_det_riwayat;
        initComponents();
        setMaximumSize(new Dimension(Integer.MAX_VALUE, 110)); // Tinggi boleh kamu sesuaikan
        setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
        setBackground(Color.WHITE);
        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        
        JLabel lblNama = new JLabel(namaKonser);
        lblNama.setFont(new Font("Arial", Font.BOLD, 16));
        lblNama.setAlignmentX(LEFT_ALIGNMENT);
        add(lblNama);
        
        JPanel row1 = new JPanel(new BorderLayout());
        row1.setOpaque(false);
        
        
        JLabel lblBand = new JLabel("Artis: " + namaBand);
        JLabel lblWaktu = new JLabel("Tanggal: " + tanggal + " | " + jam);      
        row1.add(lblBand, BorderLayout.WEST);
        row1.add(lblWaktu, BorderLayout.EAST);
        
        
        JPanel row2 = new JPanel(new BorderLayout());
        row2.setOpaque(false);
        
        JLabel lblKursi = new JLabel("Kursi: " + kategori + " / " + kursi);
        JLabel lblLokasi = new JLabel("Lokasi: " + lokasi);
        row2.add(lblKursi, BorderLayout.WEST);
        row2.add(lblLokasi, BorderLayout.EAST);        
        
        add(row1);
        add(row2);
    }

    public String getIdTiket(){
        return id_det_riwayat;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
