/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.konser_oop2.pembeli;

import com.mycompany.konser_oop2.connection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.WriterException;
import com.google.zxing.qrcode.QRCodeWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.client.j2se.MatrixToImageWriter;

import javax.swing.*;
import java.awt.image.BufferedImage;

/**
 *
 * @author Gita Aulia Hafid
 */
public class detailRiwayatKonser extends javax.swing.JFrame {
    
    private String var_pembeli;
    private String id_det_tiket;
    
    public detailRiwayatKonser(String id_det_tiket, String id_pembeli) {
        initComponents();
        panelDetail.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
        this.var_pembeli = id_pembeli;
        this.id_det_tiket = id_det_tiket;
        
            if(var_pembeli == null || var_pembeli.isEmpty() || id_det_tiket.isEmpty()){
                 new beranda(id_pembeli).setVisible(true);
                dispose();
            } else {
                 try {
                 Connection conn = connection.getConnection(); // bikin koneksi baru
                String query = "SELECT nama FROM pembeli WHERE id_pembeli = ?";
                PreparedStatement ps = conn.prepareStatement(query);
                ps.setString(1, id_pembeli);
                ResultSet rs = ps.executeQuery();
               if (rs.next()) {
            String namaPembeli = rs.getString("nama");
            usernameBook.setText(namaPembeli);
            usernameBook.setText(namaPembeli); // tampilkan nama di GUI
            
        }
       detailRiwayat(id_det_tiket, var_pembeli);
        rs.close();
        ps.close();
        conn.close();
            }catch(SQLException e){
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        berandaLbl = new javax.swing.JLabel();
        usernameBook = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelDetail = new javax.swing.JPanel();
        namaKonserLbl = new javax.swing.JLabel();
        kursiLbl = new javax.swing.JLabel();
        lokasiLbl = new javax.swing.JLabel();
        tanggalLbl = new javax.swing.JLabel();
        jamLbl = new javax.swing.JLabel();
        judulLbl = new javax.swing.JLabel();
        qrLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        berandaLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        berandaLbl.setText("BERANDA");
        berandaLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                berandaLblMouseClicked(evt);
            }
        });

        usernameBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usernameBook.setText("USERNAME");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("RIWAYAT");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("KONSERKU");

        panelDetail.setLayout(new java.awt.GridBagLayout());

        namaKonserLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namaKonserLbl.setText("ONE OK ROCK");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 50, 0, 0);
        panelDetail.add(namaKonserLbl, gridBagConstraints);

        kursiLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kursiLbl.setText("16 / regular");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 74, 32, 0);
        panelDetail.add(kursiLbl, gridBagConstraints);

        lokasiLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lokasiLbl.setText("Stadion Utama GBK, Jakarta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 53, 0, 35);
        panelDetail.add(lokasiLbl, gridBagConstraints);

        tanggalLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tanggalLbl.setText("Juni 19, 2025");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 53, 0, 0);
        panelDetail.add(tanggalLbl, gridBagConstraints);

        jamLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jamLbl.setText("4:00 Pm wib");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 19, 0, 35);
        panelDetail.add(jamLbl, gridBagConstraints);

        judulLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        judulLbl.setText("LINKIN PARK");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        panelDetail.add(judulLbl, gridBagConstraints);

        qrLbl.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 35, 0, 0);
        panelDetail.add(qrLbl, gridBagConstraints);

        backBtn.setText("Kembali");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(berandaLbl)
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                .addComponent(usernameBook))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(panelDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(backBtn)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(berandaLbl)
                    .addComponent(jLabel3)
                    .addComponent(usernameBook))
                .addGap(73, 73, 73)
                .addComponent(panelDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(backBtn)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void berandaLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berandaLblMouseClicked
        new beranda(var_pembeli).setVisible(true);
        dispose();
    }//GEN-LAST:event_berandaLblMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new riwayatPembeli(var_pembeli).setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
       new riwayatPembeli(var_pembeli).setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed


    private void detailRiwayat(String idDet, String var_pembeli){
        namaKonserLbl.setText("");
        judulLbl.setText("");
        tanggalLbl.setText("");
        jamLbl.setText("");
        lokasiLbl.setText("");
        kursiLbl.setText("");
        
         try {
              Connection conn = connection.getConnection();
            String query = "SELECT rp.id_det_tiket, rp.kursi, rp.tanggal_transaksi, rp.metode_pembayaran, dk.harga_tiket, kt.kategori_konser, k.nama_band, k.nama_konser, k.lokasi, k.jam, k.tanggal " +
                    "FROM riwayat_pembeli rp " + "JOIN detail_kategori_tiket dk on rp.id_det_tiket = dk.id_det_tiket " 
                    + "JOIN kategori_tiket kt on dk.id_kategori_tiket = kt.id_kategori_tiket "
                    + "JOIN konser k on dk.id_konser = k.id_konser "                 
                    + "where rp.id_pembeli = ? ";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, var_pembeli);
            ResultSet rs = ps.executeQuery();
            
              while(rs.next()){
                String namaKonser = rs.getString("nama_konser");
                String namaBand = rs.getString("nama_band");
                String tanggal = rs.getString("tanggal");
                String jam = rs.getString("jam");
                String lokasi = rs.getString("lokasi");
                String kursi = rs.getString("kursi");
                String kategori = rs.getString("kategori_konser");
                String id_detRiwayat = rs.getString("id_det_tiket");
                tampilkanQr(id_detRiwayat, qrLbl);
                namaKonserLbl.setText(namaBand);
                judulLbl.setText(namaKonser);
                tanggalLbl.setText(tanggal);
                jamLbl.setText(jam);
                lokasiLbl.setText(lokasi);
                kursiLbl.setText(kategori + "/" + kursi);
                
              }
         } catch ( SQLException e){
              e.printStackTrace();
         }
    }
    
    public void tampilkanQr(String data, JLabel label){
        label.setText("");
        int width = 200;
        int height = 200;
        
        QRCodeWriter qrWriter = new QRCodeWriter();
        try {
            BitMatrix bitMatrix = qrWriter.encode(data, BarcodeFormat.QR_CODE, width, height);
            BufferedImage qrImage = MatrixToImageWriter.toBufferedImage(bitMatrix);
            label.setIcon(new ImageIcon(qrImage));
        } catch(WriterException e){
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel berandaLbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jamLbl;
    private javax.swing.JLabel judulLbl;
    private javax.swing.JLabel kursiLbl;
    private javax.swing.JLabel lokasiLbl;
    private javax.swing.JLabel namaKonserLbl;
    private javax.swing.JPanel panelDetail;
    private javax.swing.JLabel qrLbl;
    private javax.swing.JLabel tanggalLbl;
    private javax.swing.JLabel usernameBook;
    // End of variables declaration//GEN-END:variables
}
