    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.konser_oop2.pembeli;

import com.mycompany.konser_oop2.connection;
import com.mycompany.konser_oop2.pembeli.cardRiwayatPanel;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Gita Aulia Hafid
 */
public class riwayatPembeli extends javax.swing.JFrame {

    private String var_pembeli;
    
    public riwayatPembeli(String id_pembeli) {
        this.var_pembeli = id_pembeli;
        initComponents();
        containerRiwayat.setLayout(new BoxLayout(containerRiwayat, BoxLayout.Y_AXIS));
      
        if(var_pembeli == null || var_pembeli.isEmpty()){
             new beranda(id_pembeli).setVisible(true);
            dispose();
        } else {
            riwayat(var_pembeli);
        }
        
    }
    
    public void riwayat(String var_pembeli){
        containerRiwayat.removeAll();
        
        try {
            Connection conn = connection.getConnection();
            String query = "SELECT rp.id_det_tiket, rp.kursi, rp.tanggal_transaksi, rp.metode_pembayaran, dk.harga_tiket, kt.kategori_konser, k.nama_band, k.nama_konser, k.lokasi, k.jam, k.tanggal " +
                    "FROM riwayat_pembeli rp " + "JOIN detail_kategori_tiket dk on rp.id_det_tiket = dk.id_det_tiket " 
                    + "JOIN kategori_tiket kt on dk.id_kategori_tiket = kt.id_kategori_tiket "
                    + "JOIN konser k on dk.id_konser = k.id_konser "                 
                    + "where rp.id_pembeli = ? ";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, var_pembeli);
            ResultSet rs = ps.executeQuery();
            
            while(rs.next()){
                String namaKonser = rs.getString("nama_konser");
                String namaBand = rs.getString("nama_band");
                String tanggal = rs.getString("tanggal");
                String jam = rs.getString("jam");
                String lokasi = rs.getString("lokasi");
                String kursi = rs.getString("kursi");
                String kategori = rs.getString("kategori_konser");
                String id_detRiwayat = rs.getString("id_det_tiket");
               
                cardRiwayatPanel card = new cardRiwayatPanel(id_detRiwayat, namaKonser, namaBand, tanggal, jam, lokasi, kursi, kategori);
                card.addMouseListener(new MouseAdapter(){
                     public void mouseClicked(MouseEvent e) {
                    new detailRiwayatKonser(card.getIdTiket(), var_pembeli).setVisible(true);
                    dispose();
                     }
                });
                containerRiwayat.add(card);
                containerRiwayat.add(Box.createRigidArea(new Dimension(0,10)));
            }
            containerRiwayat.revalidate();
            containerRiwayat.repaint();
        } catch(SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        berandaLbl = new javax.swing.JLabel();
        usernameBook = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        containerScroll = new javax.swing.JScrollPane();
        containerRiwayat = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("KONSERKU");

        berandaLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        berandaLbl.setText("BERANDA");
        berandaLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                berandaLblMouseClicked(evt);
            }
        });

        usernameBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usernameBook.setText("USERNAME");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("RIWAYAT");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout containerRiwayatLayout = new javax.swing.GroupLayout(containerRiwayat);
        containerRiwayat.setLayout(containerRiwayatLayout);
        containerRiwayatLayout.setHorizontalGroup(
            containerRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );
        containerRiwayatLayout.setVerticalGroup(
            containerRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );

        containerScroll.setViewportView(containerRiwayat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(berandaLbl)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                        .addComponent(usernameBook))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(containerScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(berandaLbl)
                    .addComponent(jLabel3)
                    .addComponent(usernameBook))
                .addGap(45, 45, 45)
                .addComponent(containerScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void berandaLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berandaLblMouseClicked
        new beranda(var_pembeli).setVisible(true);
        dispose();
    }//GEN-LAST:event_berandaLblMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new riwayatPembeli(var_pembeli).setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel berandaLbl;
    private javax.swing.JPanel containerRiwayat;
    private javax.swing.JScrollPane containerScroll;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel usernameBook;
    // End of variables declaration//GEN-END:variables
}
