    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.konser_oop2.pembeli;

/**
 *
 * @author Gita Aulia Hafid
 */
public class riwayatPembeli extends javax.swing.JFrame {

    private String var_pembeli;
    
    public riwayatPembeli(String id_pembeli) {
        this.var_pembeli = id_pembeli;
        initComponents();
        
        if(var_pembeli == null || var_pembeli.isEmpty()){
             new beranda(id_pembeli).setVisible(true);
            dispose();
        } else {
            riwayat(var_pembeli);
        }
        
    }
    
    public void riwayat(String var_pembeli){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        berandaLbl = new javax.swing.JLabel();
        usernameBook = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SIPP");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("KONSERKU");

        berandaLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        berandaLbl.setText("BERANDA");
        berandaLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                berandaLblMouseClicked(evt);
            }
        });

        usernameBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usernameBook.setText("USERNAME");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("RIWAYAT");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(berandaLbl)
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                .addComponent(usernameBook)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(berandaLbl)
                    .addComponent(jLabel3)
                    .addComponent(usernameBook))
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void berandaLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berandaLblMouseClicked
        new beranda(var_pembeli).setVisible(true);
        dispose();
    }//GEN-LAST:event_berandaLblMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new riwayatPembeli(var_pembeli).setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel berandaLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel usernameBook;
    // End of variables declaration//GEN-END:variables
}
