/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.konser_oop2;
import com.mycompany.konser_oop2.admin.loginAdmin;
import com.mycompany.konser_oop2.pembeli.beranda;
import com.mycompany.konser_oop2.pembeli.loginPembeli;
import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class landingPage extends javax.swing.JFrame {

    private String id_admin = null;
    public landingPage() {
         setTitle("Login - Aplikasi Konserku");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(800, 500);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());

        // === Panel Kiri (gambar + teks) ===
        JPanel leftPanel = new JPanel() {
            private final Image bgImage = new ImageIcon(getClass().getClassLoader().getResource("com/mycompany/konser_oop2/icon.jpg")).getImage();

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(bgImage, 0, 0, getWidth(), getHeight(), this);
                g.setColor(new Color(255, 255, 255, 230));
                g.setFont(new Font("SansSerif", Font.BOLD, 20));
                g.drawString("Selamat datang di aplikasi konserku", 20, getHeight() - 40);
            }
        };
        leftPanel.setPreferredSize(new Dimension(400, 500));
        leftPanel.setLayout(null);

        // === Panel Kanan (Login Form) ===
        JPanel rightPanel = new JPanel(new GridBagLayout());
        rightPanel.setBackground(Color.WHITE);

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.fill = GridBagConstraints.HORIZONTAL;

        // Title
        JLabel titleLabel = new JLabel("KonserKu", SwingConstants.CENTER);
        titleLabel.setFont(new Font("SansSerif", Font.BOLD, 23));
        titleLabel.setForeground(new Color(165, 87, 88));
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        rightPanel.add(titleLabel, gbc);


        // Tombol Login
        gbc.gridx = 0;
        gbc.gridy++;
        gbc.gridwidth = 2;
       JButton loginPButton = new JButton("Login Pembeli");
        rightPanel.add(loginPButton, gbc);
        
        gbc.gridx = 0;
        gbc.gridy++;
        gbc.gridwidth = 2;
        JButton loginAButton = new JButton("Login Administrator" );
        rightPanel.add(loginAButton, gbc);
        
        gbc.gridx = 0;
        gbc.gridy++;
        gbc.gridwidth = 2;
        JButton loginKButton = new JButton("Kembali" );
        rightPanel.add(loginKButton, gbc);

        // === Gabungkan Panel Kiri dan Kanan ===
        add(leftPanel, BorderLayout.WEST);
        add(rightPanel, BorderLayout.CENTER);

        // === Event Login Button ===
        loginAButton.addActionListener(e -> {
            new loginAdmin().setVisible(true);
                   dispose();
        });
        
        loginPButton.addActionListener(e -> {
            new loginPembeli().setVisible(true);
                   dispose();
        });
        
        loginKButton.addActionListener(e -> {
            new beranda(id_admin).setVisible(true);
                   dispose();
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
